<?php

declare(strict_types=1);

return [
    'permissions' => [
        'auth.me',
        'products.read',
        'products.write',
        'orders.read',
        'orders.write',
        'clients.read',
        'clients.write',
        'users.read',
        'users.write',
        'tables.read',
        'tables.write',
        'kitchen.read',
        'kitchen.write',
        'cash.read',
        'cash.write',
        'devices.write',
    ],
    'role_permissions' => [
        'SUPERADMIN' => ['*'],
        'ADMIN' => ['*'],
        'GERENTE' => ['*'],
        'CAJERO' => [
            'auth.me',
            'products.read',
            'orders.read',
            'orders.write',
            'clients.read',
            'clients.write',
            'tables.read',
            'tables.write',
            'cash.read',
            'cash.write',
            'devices.write',
        ],
        'MOZO' => [
            'auth.me',
            'products.read',
            'orders.read',
            'orders.write',
            'clients.read',
            'tables.read',
            'tables.write',
            'cash.read',
            'devices.write',
        ],
        'COCINA' => [
            'auth.me',
            'products.read',
            'orders.read',
            'orders.write',
            'kitchen.read',
            'kitchen.write',
            'devices.write',
        ],
        'SUPERVISOR' => [
            'auth.me',
            'products.read',
            'orders.read',
            'clients.read',
            'tables.read',
            'kitchen.read',
            'cash.read',
            'devices.write',
        ],
        'ENCARGADO' => [
            'auth.me',
            'products.read',
            'orders.read',
            'orders.write',
            'clients.read',
            'tables.read',
            'tables.write',
            'kitchen.read',
            'cash.read',
            'cash.write',
            'devices.write',
        ],
    ],
];
